# Generated by Django 5.2.1 on 2025-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'departure_time', 'travel_class')},
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_date',
        ),
    ]
