# Generated by Django 5.2.1 on 2025-05-15 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_engine', '0003_booking_passenger_name_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='demand_factor',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='flight_id',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='travel_class',
            field=models.CharField(default='Economy', max_length=20),
        ),
    ]
